#pragma once
#ifndef __zenApi_Base_Constant_BuildDefines_DX11_h__
#define __zenApi_Base_Constant_BuildDefines_DX11_h__

#define	ZEN_EXPORT_OR_RESOURCE_DX11	ZEN_PLATFORM_PC
#define	ZEN_EXPORT_DX11				ZEN_PLATFORM_PC
#define	ZEN_EXPORT_TEXTURE_DX11		ZEN_PLATFORM_PC
#define	ZEN_EXPORT_VERTEX_DX11		ZEN_PLATFORM_PC
#define	ZEN_EXPORT_INDEX_DX11		ZEN_PLATFORM_PC
#define	ZEN_EXPORT_SHADER_SM5_DX11	ZEN_BUILD_PC_GAMEORTOOL

#endif
