
#define	AW_EXPORT_OR_RESOURCE_DX11	ZEN_PLATFORM_PC
#define	AW_EXPORT_DX11				ZEN_PLATFORM_PC
#define	AW_EXPORT_TEXTURE_DX11		ZEN_PLATFORM_PC
#define	AW_EXPORT_VERTEX_DX11		ZEN_PLATFORM_PC
#define	AW_EXPORT_INDEX_DX11		ZEN_PLATFORM_PC
#define	AW_EXPORT_SHADER_SM5_DX11	ZEN_BUILD_PC_GAMEORTOOL
